# Generated by Django 2.0.7 on 2018-07-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diy_count', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readnum',
            name='slug_name',
            field=models.CharField(max_length=60, verbose_name='后缀名'),
        ),
    ]
